print()
import math
length_square = float(input("What is the length of the square in centimeters? "))
print(f"The area of the square in centimeters is: {length_square * length_square}")
print(f"The area of the square in meters is: {(length_square * length_square) / 100}")
print()
length_rectangle = float(input("What is the length of the rectangle in centimeters? "))
width_rectangle = float(input("What is the width of the rectangle in centimeters? "))
print(f"The area of the rectangle in centimaters is: {length_rectangle * width_rectangle}")
print(f"The area of the rectangle in meters is: {(length_rectangle * width_rectangle) / 100}")
print()
radius_circle = float(input("What is the radius of the circle in centimeters? "))
print(f"The area of the circle in centimaters is: {math.pi * (radius_circle * radius_circle)}")
print(f"The area of the circle in meters is: {(math.pi * (radius_circle * radius_circle)) / 100}")
print()
length = float(input("What is the length in centimeters? "))
print(f"The area of a square in centimeters with {length} length is: {length * length}")
print(f"The area of a square in meters with {length} length is: {(length * length) / 100}")
print(f"The area of a circle in centimeters with {length} radius is: {math.pi * (length * length)}")
print(f"The area of a circle in meters with {length} radius is: {(math.pi * (length * length)) / 100}")
print()
print(f"The volume of a cube in centimeters with {length} length is: {length * length * length}")
print(f"The volume of a cube in meters with {length} length is: {(length * length * length) / 100}")
print(f"The volume of a sphere in centimeters with {length} radius is: {(math.pi * (length * length)) * length}")
print(f"The volume of a sphere in meters with {length} radius is: {((math.pi * (length * length)) * length) / 100}")
print()