print()
print("Please enter the following information:")
print()
first_name = input("First name: ")
last_name = input("Last name: ")
email = input("Email address: ")
phone = input("Phone number: ")
job = input("Job title: ")
id  = input("ID Number: ")
hair = input("Hair color: ")
eyes = input("Eye color: ")
month = input("Month started: ")
training = input("Advanced training complete: ")
print()
print("The ID Card is:")
line = "----------" * 4
print(line)
print(f"{last_name.upper()}, {first_name.capitalize()}")
print(job.title())
print(f"ID: {id}")
print()
print(email.lower())
print(phone)
print()
print(f"Hair: {hair.capitalize():<15} Eyes: {eyes.capitalize()}")
print(f"Month: {month.capitalize():<14} Training: {training.capitalize()}")
print(line)
print()