print()
print("Please enter the following:")
print()
adjective_1 = input("adjective: ")
animal_1 = input("animal: ")
verb_1 = input("verb: ")
exclamation_1 = input("exclamation: ")
verb_2 = input("verb: ")
verb_3 = input("verb: ")
print()
print("Your story is:")
print()
print(f"The other day, I was really in trouble. It all started when I saw a very {adjective_1.lower()} {animal_1.lower()} {verb_1.lower()} down the hallway. \"{exclamation_1.capitalize()}!\" I yelled. But all I could think to do was to {verb_2.lower()} over and over. Miraculously, that caused it to stop, but not before it tried to {verb_3.lower()} right in front of my family.")
print()