# Favorite Color
print()
print("Hi! Nice to meet you!")
name = input("What is your name? ")
print("Hi, " + name + ".")
favorite_color = input("What is your favorite color? ")
print("I also like " + favorite_color + ".")
food = input("What is your favorite food? ")
print("I don't like " + food + ".")
print("Talk to you later, bye!")